In [ ]:
import numpy as np
a=np.arange(15)
b=np.arange(20)
a
b

In [ ]:
a=np.arange(15).reshape(3,5)
a

In [ ]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

In [ ]:
help(a)

In [ ]:
b=np.array([1.0,2.0,3.0,4.0])
print(b)
print(b.dtype)
print(type(b))

In [ ]:
c=np.eye(10)
dtype=np.float64
c

In [ ]:
d =np.linspace(-1,2,15,endpoint=True)
print(d)

In [ ]:
e=np.logspace(-1,2,15,endpoint=True,base=10)
print(e)

In [ ]:
help(np.logspace)

In [ ]:
f=np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)
f

In [ ]:
#array operations
a=np.arange(12).reshape(3,4)
print(a)

In [ ]:
a*2

In [ ]:
a+a

In [ ]:
a*a

In [ ]:
b=a.transpose()
b

In [ ]:
a@b

In [ ]:
print(a)
a.sum(axis=1)

In [ ]:
a.sum()

In [ ]:
print(a.min(),a.max())

In [ ]:
#universal function
b=a*np.pi/12.0

In [ ]:
c=np.cos(b)
print(c)

In [ ]:
d=b+c

In [ ]:
print(d)

In [ ]:
#array slicing
a=a.all()
a

In [ ]:
d[2]

In [ ]:
print(d[1:2])


In [ ]:
d[2:4]

In [ ]:

d[:]

In [ ]:
#multidimensional array
a=np.arange(15).reshape(3,5)
a

In [ ]:
a[1,1]

In [ ]:
a[0:2,0:2]

In [ ]:
a[:,1]

In [ ]:
a=a.flatten()
print(a)

In [ ]:
#print(a)
for r in a:
    print(r)
a=np.arange(15).reshape(3,5)
print(a)

In [ ]:
for e in a.flat:
    print(a)

In [ ]:

help(a.flatten())

In [ ]:
#copying arrays
a=np.arange(10)
print(a)

In [ ]:
b=a
b is a

In [ ]:
b.shape=(2,5)
print(b)
a.shape

In [ ]:
b is a

In [ ]:
print(a)

In [ ]:
a=np.arange(12)

In [ ]:
c=a[:]
a.shape=(3,4)

In [ ]:
print(a)
print(c)

In [ ]:
c[1]=-1
print(a)
print(c)



In [ ]:
d=c[3:8]
print(d)

In [ ]:
d[:]

In [ ]:
print(a)
print(c)
print(d)

In [ ]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

In [ ]:
d=a.copy()
d[:,:]=0.0
print(a)
print(d)

In [ ]:
#boolean indexing
a=np.arange(12).reshape(3,4)
a

In [ ]:
a[a>4]=0

In [ ]:
a

In [ ]:
a

In [ ]:
a[a==0]=-1
a

In [ ]:
a==-1

In [ ]:
a=np.arange(12).reshape(3,4)
a[np.logical_and(a>3,a<=9)]=0
a

In [ ]:
a>4

In [ ]:
#avoiding loops 
m=32
n=64
xmin=ymin=0.0
xmax=ymax=1.0
x=np.linspace(xmin,xmax,m,endpoint=False)
y=np.linspace(ymin,ymax,n,endpoint=False)
print(x)
print(y)
y

In [ ]:
import time
import numpy as np
m=32
n=64
x=np.linspace(0.0,1.0,m,endpoint=False)
y=np.linspace(0.0,1.0,n,endpoint=False)

In [ ]:
to=time.time()
g=np.zeros((m,n))
for i in range(m):
    for j in range(n):
        g[i,j]=np.sin(2.0*np.pi*x[i]*y[j])
t1=time.time()
print("time elapsed :{}s".format(t1-to))

In [ ]:
x2d,y2d=np.meshgrid(x,y,indexing="ij")
print(x2d[:,0])
print(x2d[0,:])
print(y2d[:,0])
print(y2d[0,:])

In [ ]:
t0=time.time()
g2=np.sin(2.0*np.pi*x2d*y2d)
t1=time.time()
print("time elapsed :{}s".format(t1-t0))

In [ ]:
#concatenating strings
x=np.array([1,2,3,4])
y=np.array([4,3,2,12])
np.concatenate([y,x])

In [ ]:
z=[9,4,6]
print(np.concatenate([x,y,z]))

In [ ]:
grid=np.array([10,20,30,40,50,60])

In [ ]:
np.concatenate([grid,grid])

In [ ]:
#splitting of arrays
x=[1,2,3,4,4,3,2,1,9,4,6]
x1,x2,x3,x4=np.split(x,[3,5,8])

In [10]:
grid= np.arange(25).reshape((5,5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [12]:
#aggregates
x=np.arange(1,9)
print(x)
np.add.reduce(x)

[1 2 3 4 5 6 7 8]


36

In [13]:
np.multiply.reduce(x)

40320

In [14]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [15]:
np.multiply.accumulate(x)

array([    1,     2,     6,    24,   120,   720,  5040, 40320],
      dtype=int32)

In [9]:
import numpy as np